
-- Add fields for deep HLS segment scanner results
ALTER TABLE IF EXISTS streams
ADD COLUMN IF NOT EXISTS master_m3u8_load_success BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS media_playlist_load_success BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS playlist_refresh_success BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS segment_load_success_1 BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS segment_load_success_2 BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS segment_load_success_3 BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS segment_response_time REAL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS segment_content_type TEXT,
ADD COLUMN IF NOT EXISTS segment_size INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS redirects_followed INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS final_url TEXT,
ADD COLUMN IF NOT EXISTS required_headers JSONB DEFAULT '{}'::jsonb,
ADD COLUMN IF NOT EXISTS http_error_code INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS token_expiry_detected BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS html_error_page_detected BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS geo_blocked BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS drm_protected BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS codec_issue_detected BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS scanner_status TEXT DEFAULT 'unknown';

-- Add fields for stream stability score
ALTER TABLE IF EXISTS streams
ADD COLUMN IF NOT EXISTS startup_success_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS played_30s_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS played_2min_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS played_5min_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS buffering_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS avg_buffer_duration REAL DEFAULT 0.0,
ADD COLUMN IF NOT EXISTS segment_failure_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS fail_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS success_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_success_timestamp TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS last_failure_timestamp TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS stability_score INTEGER DEFAULT 0;

-- Add fields for backup stream requirement and important channels
ALTER TABLE IF EXISTS channels
ADD COLUMN IF NOT EXISTS is_important BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS needs_manual_verification BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS manual_verification_reason TEXT;

-- Add field for restream_enabled and is_legal_source to streams
ALTER TABLE IF EXISTS streams
ADD COLUMN IF NOT EXISTS restream_enabled BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS is_legal_source BOOLEAN DEFAULT FALSE;
