const express = require('express');
const router = express.Router();
const proxyController = require('../controllers/proxyController');
const { optionalAuth } = require('../middleware/auth');

// Proxy routes use optionalAuth for the initial request.
// The auth middleware validates JWT if present. If missing (e.g. dropped by 
// media player on HLS reload), proxyController verifies the IP against a short-lived cache.
// Additional checks (license active, channel visible, stream allowed) are
// performed inside proxyController before serving any content.
// Manifest: require JWT auth so only licensed users can proxy streams.
// media_kit passes the Bearer token as a header for the initial manifest request;
// rewritten segment URLs carry an encrypted segToken so segments need no header.
router.get('/:streamId/master.m3u8', optionalAuth, proxyController.proxyManifest);
// Segments: token in URL carries auth — no Bearer needed (libmpv may not forward headers)
// The encrypted segToken was generated by proxyManifest and embeds expiry + streamId binding
router.get('/segment/:streamId/:segToken', proxyController.proxySegment);

module.exports = router;
