const express = require('express');
const router = express.Router();
const proxyController = require('../controllers/proxyController');
const authMiddleware = require('../middleware/auth');

// Proxy routes require authentication — no public access to stream proxying.
// The auth middleware validates JWT and checks that the user is active.
// Additional checks (license active, channel visible, stream allowed) are
// performed inside proxyController before serving any content.
// Manifest: bypassed auth temporarily
router.get('/:streamId/master.m3u8', proxyController.proxyManifest);
// Segments: token in URL carries auth — no Bearer needed (libmpv may not forward headers)
// The encrypted segToken was generated by proxyManifest and embeds expiry + streamId binding
router.get('/segment/:streamId/:segToken', proxyController.proxySegment);

module.exports = router;
