const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/smoothPlaybackController');
const { apiLimiter } = require('../middleware/rateLimit');

// Serve delayed HLS playlists and segments. Auth is handled via signed ?t= token
// generated by getSmoothPlayback so media players can access without Authorization header.
router.get('/:channelId/playlist.m3u8', apiLimiter, ctrl.servePlaylist);
router.get('/:channelId/media.m3u8', apiLimiter, ctrl.serveMediaPlaylist);
router.get('/:channelId/segments/:segmentName', apiLimiter, ctrl.serveSegment);

module.exports = router;
